const universities = [
  {
    web_pages: ['http://www.aauj.edu/'],
    name: 'Arab American University - Jenin',
    alpha_two_code: 'PS',
    'state-province': 'Jenin',
    domains: ['aauj.edu'],
    country: 'Palestine, State of',
  },
  {
    web_pages: ['http://www.alaqsa.edu.ps/'],
    name: 'Al-Aqsa University',
    alpha_two_code: 'PS',
    'state-province': 'Khan Younis',
    domains: ['alaqsa.edu.ps'],
    country: 'Palestine, State of',
  },
  {
    web_pages: ['http://www.alazhar.edu.ps/'],
    name: 'Al-Azhar University of Gaza',
    alpha_two_code: 'PS',
    'state-province': 'Gaza',
    domains: ['alazhar.edu.ps'],
    country: 'Palestine, State of',
  },
  {
    web_pages: ['http://www.alquds.edu/'],
    name: 'Al-Quds University - The Arab University in Jerusalem',
    alpha_two_code: 'PS',
    'state-province': 'Jerusalem',
    domains: ['alquds.edu'],
    country: 'Palestine, State of',
  },
  {
    web_pages: ['http://www.bethlehem.edu/'],
    name: 'Bethlehem University',
    alpha_two_code: 'PS',
    'state-province': 'Bethlehem',
    domains: ['bethlehem.edu'],
    country: 'Palestine, State of',
  },
  {
    web_pages: ['http://www.birzeit.edu/'],
    name: 'Birzeit University',
    alpha_two_code: 'PS',
    'state-province': 'Ramallah',
    domains: ['birzeit.edu'],
    country: 'Palestine, State of',
  },
  {
    web_pages: ['http://www.hebron.edu/'],
    name: 'Hebron University',
    alpha_two_code: 'PS',
    'state-province': 'Hebron',
    domains: ['hebron.edu'],
    country: 'Palestine, State of',
  },
  {
    web_pages: ['http://www.iugaza.edu.ps/'],
    name: 'Islamic University of Gaza',
    alpha_two_code: 'PS',
    'state-province': 'Gaza',
    domains: ['iugaza.edu.ps'],
    country: 'Palestine, State of',
  },
  {
    web_pages: ['http://www.najah.edu/'],
    name: 'An-Najah National University',
    alpha_two_code: 'PS',
    'state-province': 'Nablus',
    domains: ['najah.edu'],
    country: 'Palestine, State of',
  },
  {
    web_pages: ['http://www.ppu.edu/'],
    name: 'Palestine Polytechnic University',
    alpha_two_code: 'PS',
    'state-province': 'Hebron',
    domains: ['ppu.edu'],
    country: 'Palestine, State of',
  },
  {
    web_pages: ['http://www.ptcdb.edu.ps/'],
    name: 'Palestine Technical College-Dier Elbalah',
    alpha_two_code: 'PS',
    'state-province': 'Dier Elbalah',
    domains: ['ptcdb.edu.ps'],
    country: 'Palestine, State of',
  },
  {
    web_pages: ['http://www.ptuk.edu.ps/'],
    name: 'Palestine Technical University - Kadoorie',
    alpha_two_code: 'PS',
    'state-province': 'Tulkarm',
    domains: ['ptuk.edu.ps'],
    country: 'Palestine, State of',
  },
  {
    web_pages: ['http://www.qou.edu/'],
    name: 'Al-Quds Open University',
    alpha_two_code: 'PS',
    'state-province': 'Rafah',
    domains: ['qou.edu'],
    country: 'Palestine, State of',
  },
  {
    web_pages: ['http://www.ucas.edu.ps/'],
    name: 'University College of Applied Sciences',
    alpha_two_code: 'PS',
    'state-province': 'Gaza',
    domains: ['ucas.edu.ps'],
    country: 'Palestine, State of',
  },
  {
    web_pages: ['http://www.uou.edu.ps/'],
    name: 'Ummah University',
    alpha_two_code: 'PS',
    'state-province': 'Gaza',
    domains: ['uou.edu.ps'],
    country: 'Palestine, State of',
  },
  {
    web_pages: ['http://www.up.edu.ps/'],
    name: 'University of Palestine',
    alpha_two_code: 'PS',
    'state-province': 'Al-Zahra',
    domains: ['up.edu.ps'],
    country: 'Palestine, State of',
  },
];
